[package]
name = "qr"
version = "0.1.0"
authors = ["taku-y <taku.yoshioka.4096@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tch = "=0.4.0"
ndarray = "=0.14"
csv = "1.1.3"
ndarray-csv = "0.5.1"
